import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const API_LIST_URL = "https://open.wangdian.cn/qjb/open/apidoc";
const DOC_BASE_URL = "https://open.wangdian.cn/qjb/open/apidoc/doc?path=";

interface EndpointRow {
  method: string;
  category: string;
  name: string;
  description: string;
  clientPath: string;
  docUrl: string;
}

const html = await fetchText(API_LIST_URL);
const endpoints = parseEndpointRows(html);

if (endpoints.length === 0) {
  throw new Error("No WDT endpoints were parsed from the API document.");
}

const outputPath = resolve(import.meta.dir, "../src/endpoints.ts");
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, renderEndpointsFile(endpoints));

console.log(`Generated ${endpoints.length} endpoints at ${outputPath}`);

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function parseEndpointRows(source: string): EndpointRow[] {
  const rows: EndpointRow[] = [];
  const categoryRegex = /<div mname="([^"]+)">([\s\S]*?)(?=<div mname=|<\/div>\s*<\/div>\s*<\/div>)/g;
  let categoryMatch: RegExpExecArray | null;

  while ((categoryMatch = categoryRegex.exec(source))) {
    const category = decodeHtml(categoryMatch[1]).trim();
    const section = categoryMatch[2];
    const rowRegex =
      /<tr><td><a href="apidoc\/doc\?path=([^"]+)">([^<]+)<\/a><\/td><td>([\s\S]*?)<\/td><td>([\s\S]*?)<\/td><td>([\s\S]*?)<\/td><\/tr>/g;
    let rowMatch: RegExpExecArray | null;

    while ((rowMatch = rowRegex.exec(section))) {
      const method = decodeHtml(rowMatch[1]).trim();
      rows.push({
        method,
        category,
        name: cleanCell(rowMatch[3]),
        description: cleanCell(rowMatch[4]),
        clientPath: cleanCell(rowMatch[5]),
        docUrl: `${DOC_BASE_URL}${encodeURIComponent(method)}`,
      });
    }
  }

  return dedupeByMethod(rows);
}

function cleanCell(value: string): string {
  return decodeHtml(value.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ")).trim();
}

function decodeHtml(value: string): string {
  return value
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function dedupeByMethod(rows: EndpointRow[]): EndpointRow[] {
  const seen = new Set<string>();
  return rows.filter((row) => {
    if (seen.has(row.method)) {
      return false;
    }
    seen.add(row.method);
    return true;
  });
}

function renderEndpointsFile(rows: EndpointRow[]): string {
  const entries = rows
    .map(
      (row) => `  ${JSON.stringify(row.method)}: ${JSON.stringify(row)},`,
    )
    .join("\n");

  const contracts = rows
    .map(
      (row) =>
        `  ${JSON.stringify(row.method)}: { request: WdtRequestBody; response: WdtApiResponse };`,
    )
    .join("\n");

  return `/* eslint-disable */\n// This file is generated by scripts/generate-endpoints.ts.\n// Source: ${API_LIST_URL}\n\nimport type { WdtApiResponse, WdtEndpointMeta, WdtRequestBody } from "./types";\n\nexport const WDT_ENDPOINTS = {\n${entries}\n} as const satisfies Record<string, WdtEndpointMeta>;\n\nexport type WdtMethod = keyof typeof WDT_ENDPOINTS;\n\nexport interface WdtEndpointMap {\n${contracts}\n}\n`;
}
