/* eslint-disable */
// This file is generated by scripts/generate-endpoints.ts.
// Source: https://open.wangdian.cn/qjb/open/apidoc

import type { WdtApiResponse, WdtEndpointMeta, WdtRequestBody } from "./types";

export const WDT_ENDPOINTS = {
  "wms.stockout.Sales.queryWithDetail": {"method":"wms.stockout.Sales.queryWithDetail","category":"订单类","name":"销售出库单查询","description":"为了达到保护用户隐私数据安全的目的，本接口中涉及到用户隐私的字段数据仅自有平台订单返回，具体字段详见下述“隐私字段列表”。","clientPath":"仓储-销售出库-销售出库单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.queryWithDetail"},
  "sales.LogisticsSync.update": {"method":"sales.LogisticsSync.update","category":"订单类","name":"物流同步状态回传","description":"物流同步状态回传","clientPath":"销售-信息同步-物流同步","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.LogisticsSync.update"},
  "sales.RawTrade.pushSelf": {"method":"sales.RawTrade.pushSelf","category":"订单类","name":"原始单推送","description":"①推送销售订单给ERP ②更新已推送成功的销售订单","clientPath":"销售--订单管理--原始订单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.pushSelf"},
  "sales.TradeQuery.queryWithDetail": {"method":"sales.TradeQuery.queryWithDetail","category":"订单类","name":"订单查询","description":"获取ERP的销售订单信息","clientPath":"销售-订单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.queryWithDetail"},
  "sales.LogisticsSync.getSyncListExt": {"method":"sales.LogisticsSync.getSyncListExt","category":"订单类","name":"待同步列表查询","description":"查询待同步物流列表","clientPath":"销售-物流同步","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.LogisticsSync.getSyncListExt"},
  "wms.stockout.Sales.weighingExt": {"method":"wms.stockout.Sales.weighingExt","category":"订单类","name":"重量回传","description":"自动化称重机、自动化分拣系统、仓储设备控制系统等称重以后，将重量回传写入旺店通ERP销售出库单","clientPath":"仓储--销售出库单--称重","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.weighingExt"},
  "wms.stockout.Sales.onceWeighing": {"method":"wms.stockout.Sales.onceWeighing","category":"订单类","name":"重量回传2","description":"自动化称重机、自动化分拣系统、仓储设备控制系统等称重以后，将重量回传写入旺店通ERP销售出库单，并返回部分相关信息","clientPath":"仓储--销售出库单--称重","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.onceWeighing"},
  "finance.invoice.InvoiceOrder.search": {"method":"finance.invoice.InvoiceOrder.search","category":"订单类","name":"发票信息查询","description":"获取发票信息","clientPath":"账款-发票管理-发票管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.invoice.InvoiceOrder.search"},
  "finance.invoice.InvoiceOrder.updateInvoice": {"method":"finance.invoice.InvoiceOrder.updateInvoice","category":"订单类","name":"发票信息更新","description":"更新发票信息","clientPath":"账款--发票管理--发票管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.invoice.InvoiceOrder.updateInvoice"},
  "finance.RawPayment.search": {"method":"finance.RawPayment.search","category":"订单类","name":"平台账单查询","description":"获取ERP内的平台账单","clientPath":"账款-收款付款-平台账单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.RawPayment.search"},
  "finance.RawPayment.push": {"method":"finance.RawPayment.push","category":"订单类","name":"平台账单推送","description":"推送平台账单给ERP","clientPath":"账款-收款付款-平台账单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.RawPayment.push"},
  "sales.StockSync.cancelSync": {"method":"sales.StockSync.cancelSync","category":"订单类","name":"取消当前同步","description":"取消库存同步","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.cancelSync"},
  "sales.StockSync.syncFail": {"method":"sales.StockSync.syncFail","category":"订单类","name":"库存同步失败","description":"库存同步失败时调用","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.syncFail"},
  "sales.StockSync.syncSuccess": {"method":"sales.StockSync.syncSuccess","category":"订单类","name":"库存同步成功","description":"库存同步成功时调用","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.syncSuccess"},
  "sales.StockSync.getSelfWaitSyncIdListOpen": {"method":"sales.StockSync.getSelfWaitSyncIdListOpen","category":"订单类","name":"获取自有平台货品需要同步信息","description":"获取自有平台货品需要同步信息","clientPath":"货品-平台货品","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.getSelfWaitSyncIdListOpen"},
  "wms.stockout.Sales.queryHistoryWithDetail": {"method":"wms.stockout.Sales.queryHistoryWithDetail","category":"订单类","name":"历史销售出库单查询","description":"获取ERP历史销售出库单信息","clientPath":"仓储-销售出库-历史销售出库单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.queryHistoryWithDetail"},
  "sales.TradeQuery.queryHistoryWithDetail": {"method":"sales.TradeQuery.queryHistoryWithDetail","category":"订单类","name":"历史订单查询","description":"获取ERP的历史销售订单信息","clientPath":"销售-历史订单-历史订单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.queryHistoryWithDetail"},
  "finance.AlipayAccountCheck.search": {"method":"finance.AlipayAccountCheck.search","category":"订单类","name":"平台对账单查询","description":"获取ERP平台对账单信息","clientPath":"账款--收款付款--平台对账","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.AlipayAccountCheck.search"},
  "sales.RawTrade.search": {"method":"sales.RawTrade.search","category":"订单类","name":"原始单查询","description":"获取ERP原始订单数据","clientPath":"销售--订单管理--原始订单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.search"},
  "sales.TradeQuery.getTradeMergedLog": {"method":"sales.TradeQuery.getTradeMergedLog","category":"订单类","name":"被合并订单查询","description":"查询被合并订单信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.getTradeMergedLog"},
  "finance.Payment.search": {"method":"finance.Payment.search","category":"订单类","name":"收付款单查询","description":"获取ERP内收付款单信息","clientPath":"账款--收款付款--收付款单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.Payment.search"},
  "wms.stockout.Sales.onceWeighingByNo": {"method":"wms.stockout.Sales.onceWeighingByNo","category":"订单类","name":"重量回传3","description":"自动化称重机、自动化分拣系统、仓储设备控制系统等称重以后，将重量回传写入旺店通ERP销售出库单，并返回部分相关信息","clientPath":"仓储--销售出库单--称重","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.onceWeighingByNo"},
  "sales.StockSync.calcStock": {"method":"sales.StockSync.calcStock","category":"订单类","name":"库存同步计算查询","description":"计算自有平台货品应该同步的库存，原sales.StockSync.calcStockWithAuth替代接口","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.calcStock"},
  "wms.stockout.Sales.salesWeighing": {"method":"wms.stockout.Sales.salesWeighing","category":"订单类","name":"重量回传4","description":"外部应用回传包裹重量\\包裹长宽高\\发货","clientPath":"仓储--销售出库单--称重","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.salesWeighing"},
  "sales.TradeEdit.modifyRemark": {"method":"sales.TradeEdit.modifyRemark","category":"订单类","name":"订单客服备注修改","description":"修改未审核订单客服备注，一次最多100条","clientPath":"销售--订单审核","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeEdit.modifyRemark"},
  "wms.stockout.Sales.searchLogistics": {"method":"wms.stockout.Sales.searchLogistics","category":"订单类","name":"物流单查询","description":"查询包含多物流的出库物流单信息","clientPath":"账款--单据结算--邮资结算--物流单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.searchLogistics"},
  "sales.RawTrade.searchHistory": {"method":"sales.RawTrade.searchHistory","category":"订单类","name":"历史原始单查询","description":"获取被归档的原始单数据","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.searchHistory"},
  "sales.jit.JitRefund.search": {"method":"sales.jit.JitRefund.search","category":"订单类","name":"JIT退货单查询","description":"获取ERP内JIT退货单信息","clientPath":"销售--唯品会JIT--JIT退货单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.jit.JitRefund.search"},
  "sales.RawTrade.pushSelf2": {"method":"sales.RawTrade.pushSelf2","category":"订单类","name":"原始单推送2","description":"推送自有平台订单给ERP","clientPath":"销售--订单管理--原始订单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.pushSelf2"},
  "wms.stockout.Sales.searchPositionDetail": {"method":"wms.stockout.Sales.searchPositionDetail","category":"订单类","name":"销售出库实际出库明细查询","description":"获取销售出库实际出库明细数据","clientPath":"仓储--销售出库--销售出库信息--实际出库明细","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.searchPositionDetail"},
  "sales.Payment.queryWithDetail": {"method":"sales.Payment.queryWithDetail","category":"订单类","name":"销售收付单查询","description":"获取ERP内销售收付单数据","clientPath":"销售--销售收付单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.Payment.queryWithDetail"},
  "sales.TradeImport.upload": {"method":"sales.TradeImport.upload","category":"订单类","name":"已完成订单推送","description":"推送已完成订单给ERP","clientPath":"销售-新增订单-订单导入","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeImport.upload"},
  "wms.stockout.Sales.searchCancel": {"method":"wms.stockout.Sales.searchCancel","category":"订单类","name":"已取消出库单查询","description":"获取已取消的销售出库单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.searchCancel"},
  "sales.TradeQuery.getLog": {"method":"sales.TradeQuery.getLog","category":"订单类","name":"订单日志查询","description":"查询订单日志","clientPath":"销售--订单管理--订单管理-tab订单日志","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.getLog"},
  "setting.CustomAttr.getTradeLabel": {"method":"setting.CustomAttr.getTradeLabel","category":"订单类","name":"订单标签查询","description":"获取订单标签数据","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.CustomAttr.getTradeLabel"},
  "sales.TradeEdit.toException": {"method":"sales.TradeEdit.toException","category":"订单类","name":"订单转异常订单","description":"将订单转入异常订单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeEdit.toException"},
  "sales.StockSync.batchCalcStock": {"method":"sales.StockSync.batchCalcStock","category":"订单类","name":"库存同步计算查询（批量）","description":"批量获取库存同步结果","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.batchCalcStock"},
  "sales.TradeQuery.querySelfOrderWithDetail": {"method":"sales.TradeQuery.querySelfOrderWithDetail","category":"订单类","name":"订单查询（仅返回自有平台、线下平台订单信息）","description":"仅返回自有平台、线下平台订单信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.querySelfOrderWithDetail"},
  "sales.RawTrade.searchHistorySelfOrder": {"method":"sales.RawTrade.searchHistorySelfOrder","category":"订单类","name":"历史原始单查询（仅返回自有平台、线下平台订单）","description":"仅返回自有平台及线下平台订单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.searchHistorySelfOrder"},
  "sales.TradeQuery.queryHistorySelfOrderWithDetail": {"method":"sales.TradeQuery.queryHistorySelfOrderWithDetail","category":"订单类","name":"历史订单查询（仅返回自有平台、线下平台订单）","description":"仅返回自有平台、线下平台订单信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.queryHistorySelfOrderWithDetail"},
  "sales.RawTrade.searchSelfOrder": {"method":"sales.RawTrade.searchSelfOrder","category":"订单类","name":"原始单查询（仅返回自有平台、线下平台订单）","description":"仅返回自有平台、线下平台订单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.searchSelfOrder"},
  "sales.TradeQuery.getLog2": {"method":"sales.TradeQuery.getLog2","category":"订单类","name":"订单日志批量查询","description":"","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.getLog2"},
  "setting.Logistics.queryLogistics": {"method":"setting.Logistics.queryLogistics","category":"基础类","name":"物流公司查询","description":"获取ERP的物流公司档案资料","clientPath":"设置-基本设置-物流","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Logistics.queryLogistics"},
  "setting.PurchaseProvider.queryDetail": {"method":"setting.PurchaseProvider.queryDetail","category":"基础类","name":"供应商查询","description":"获取ERP的供应商档案资料","clientPath":"设置-基本设置-供应商","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.PurchaseProvider.queryDetail"},
  "setting.Warehouse.queryWarehouse": {"method":"setting.Warehouse.queryWarehouse","category":"基础类","name":"仓库查询","description":"获取ERP的仓库档案资料","clientPath":"设基-基本设置-仓库","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Warehouse.queryWarehouse"},
  "setting.Shop.queryShop": {"method":"setting.Shop.queryShop","category":"基础类","name":"店铺查询","description":"获取ERP的店铺档案资料","clientPath":"设置-基本设置-店铺","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Shop.queryShop"},
  "setting.PurchaseProvider.push": {"method":"setting.PurchaseProvider.push","category":"基础类","name":"供应商信息推送","description":"推送供应商档案资料给ERP","clientPath":"设置-基本设置-供应商","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.PurchaseProvider.push"},
  "setting.Shop.updateShop": {"method":"setting.Shop.updateShop","category":"基础类","name":"店铺更新","description":"更新ERP的店铺档案资料","clientPath":"设置-基本设置-店铺","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Shop.updateShop"},
  "setting.Employee.search": {"method":"setting.Employee.search","category":"基础类","name":"员工查询","description":"获取ERP内员工信息","clientPath":"设置--基本设置-员工","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Employee.search"},
  "setting.strategy.VirtualWarehouse.warehouseSearch": {"method":"setting.strategy.VirtualWarehouse.warehouseSearch","category":"基础类","name":"虚拟仓仓库查询","description":"获取ERP虚拟仓仓库信息","clientPath":"设置--策略设置--虚拟仓策略--虚拟仓","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.warehouseSearch"},
  "setting.OperationReason.search": {"method":"setting.OperationReason.search","category":"基础类","name":"退换原因查询","description":"查询客户端的退换原因","clientPath":"设置-基本设置-原因列表-退换说明","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.OperationReason.search"},
  "setting.Address.provinceSearch": {"method":"setting.Address.provinceSearch","category":"基础类","name":"地址查询-省","description":"查询省份信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Address.provinceSearch"},
  "setting.Address.citySearch": {"method":"setting.Address.citySearch","category":"基础类","name":"地址查询-市","description":"查询城市信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Address.citySearch"},
  "setting.Address.districtSearch": {"method":"setting.Address.districtSearch","category":"基础类","name":"地址查询-区","description":"查询区域信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Address.districtSearch"},
  "setting.strategy.VirtualWarehouse.query": {"method":"setting.strategy.VirtualWarehouse.query","category":"基础类","name":"虚拟仓信息查询","description":"获取虚拟仓、店铺、实体仓的关联关系","clientPath":"设置--策略设置--虚拟仓策略--虚拟仓","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.query"},
  "sales.TradeEdit.uploadChangeGoodsByApi": {"method":"sales.TradeEdit.uploadChangeGoodsByApi","category":"基础类","name":"优先级换货策略写入和更新","description":"","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeEdit.uploadChangeGoodsByApi"},
  "goods.Goods.push": {"method":"goods.Goods.push","category":"货品类","name":"货品推送","description":"①推送货品资料给ERP ②更新ERP货品档案资料","clientPath":"货品-货品档案","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.push"},
  "goods.Suite.search": {"method":"goods.Suite.search","category":"货品类","name":"组合装查询","description":"获取ERP中组合装界面的组合装资料","clientPath":"货品-组合装","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Suite.search"},
  "goods.Goods.queryWithSpec": {"method":"goods.Goods.queryWithSpec","category":"货品类","name":"货品档案查询","description":"获取ERP的货品档案资料","clientPath":"货品-货品档案","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.queryWithSpec"},
  "goods.ApiGoods.search": {"method":"goods.ApiGoods.search","category":"货品类","name":"平台货品查询","description":"获取ERP内平台货品资料","clientPath":"货品-平台货品","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.ApiGoods.search"},
  "goods.ApiGoods.upload": {"method":"goods.ApiGoods.upload","category":"货品类","name":"平台货品推送","description":"推送自研商城平台货品给ERP","clientPath":"货品--平台货品","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.ApiGoods.upload"},
  "process.Bom.upload": {"method":"process.Bom.upload","category":"货品类","name":"物料清单推送","description":"推送物料清单给旺店通","clientPath":"货品--生产--物料清单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Bom.upload"},
  "process.Process.upload": {"method":"process.Process.upload","category":"货品类","name":"生产单推送","description":"推送生产单给ERP","clientPath":"货品--生产--生产开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Process.upload"},
  "process.Process.search": {"method":"process.Process.search","category":"货品类","name":"生产单查询","description":"获取ERP内生产单信息","clientPath":"货品--生产--生产单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Process.search"},
  "goods.GoodsClass.search": {"method":"goods.GoodsClass.search","category":"货品类","name":"货品分类查询","description":"获取ERP货品分类信息","clientPath":"货品--货品分类","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsClass.search"},
  "goods.GoodsBrand.search": {"method":"goods.GoodsBrand.search","category":"货品类","name":"品牌查询","description":"获取ERP内货品品牌信息","clientPath":"货品--货品品牌","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsBrand.search"},
  "goods.Suite.upload2": {"method":"goods.Suite.upload2","category":"货品类","name":"组合装创建/更新","description":"创建组合装或更新ERP内组合装信息","clientPath":"货品--组合装管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Suite.upload2"},
  "goods.Category.search": {"method":"goods.Category.search","category":"货品类","name":"平台类目查询","description":"获取ERP平台类目信息","clientPath":"货品--平台类目","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Category.search"},
  "goods.Goods.batchPush": {"method":"goods.Goods.batchPush","category":"货品类","name":"货品批量推送","description":"1、批量推送货品资料给ERP 2、更新ERP货品档案资料","clientPath":"货品-货品档案","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.batchPush"},
  "process.Bom.search": {"method":"process.Bom.search","category":"货品类","name":"物料清单查询","description":"获取ERP内的物料清单数据","clientPath":"货品--生产--物料清单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Bom.search"},
  "goods.Barcode.upload": {"method":"goods.Barcode.upload","category":"货品类","name":"条码上传","description":"新建或更新条码","clientPath":"货品-货品条码","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Barcode.upload"},
  "goods.Goods.push2": {"method":"goods.Goods.push2","category":"货品类","name":"货品推送2","description":"①推送货品资料给ERP ②更新ERP货品档案资料","clientPath":"货品-货品档案","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.push2"},
  "goods.GoodsClass.upload": {"method":"goods.GoodsClass.upload","category":"货品类","name":"新建分类","description":"新建货品分类","clientPath":"货品-货品分类","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsClass.upload"},
  "goods.GoodsBrand.upload": {"method":"goods.GoodsBrand.upload","category":"货品类","name":"货品品牌新建/更新","description":"新建/更新品牌信息","clientPath":"货品--货品品牌","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsBrand.upload"},
  "finance.settle.process.search": {"method":"finance.settle.process.search","category":"货品类","name":"生产结算单查询","description":"获取生产结算单信息","clientPath":"账款--单据结算--生产结算","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.process.search"},
  "purchase.ProviderGoods.queryDetail": {"method":"purchase.ProviderGoods.queryDetail","category":"采购类","name":"供应商货品查询","description":"获取ERP中供应商货品界面的供应商货品资料","clientPath":"采购-供应商货品","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.ProviderGoods.queryDetail"},
  "purchase.PurchaseReturn.queryWithDetail": {"method":"purchase.PurchaseReturn.queryWithDetail","category":"采购类","name":"采购退货单及明细查询","description":"获取ERP的采购退货单信息","clientPath":"采购-采购退货单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.queryWithDetail"},
  "purchase.PurchaseReturn.cancelOrder": {"method":"purchase.PurchaseReturn.cancelOrder","category":"采购类","name":"采购退货单取消","description":"推送取消已生成的采购退货单据给ERP。","clientPath":"采购-采购退货开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.cancelOrder"},
  "purchase.PurchaseReturn.createOrder": {"method":"purchase.PurchaseReturn.createOrder","category":"采购类","name":"采购退货单新建","description":"推送采购退货单据给ERP","clientPath":"采购-采购退货开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.createOrder"},
  "wms.stockin.Purchase.upload": {"method":"wms.stockin.Purchase.upload","category":"采购类","name":"采购入库单推送","description":"推送采购单对应的入库单给ERP","clientPath":"仓储-入库管理-采购入库-入库开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.upload"},
  "purchase.PurchaseOrder.queryWithDetail": {"method":"purchase.PurchaseOrder.queryWithDetail","category":"采购类","name":"采购单及明细查询","description":"获取ERP的采购单信息","clientPath":"采购→采购单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.queryWithDetail"},
  "purchase.PurchaseOrder.createOrder": {"method":"purchase.PurchaseOrder.createOrder","category":"采购类","name":"采购单新建","description":"推送采购单据给ERP","clientPath":"采购-采购开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.createOrder"},
  "finance.settle.Purchase.search": {"method":"finance.settle.Purchase.search","category":"采购类","name":"采购结算单查询","description":"获取ERP采购结算单信息","clientPath":"账款-单据结算-采购结算","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Purchase.search"},
  "wms.stockin.Purchase.queryWithDetail": {"method":"wms.stockin.Purchase.queryWithDetail","category":"采购类","name":"采购入库单查询","description":"获取ERP采购单对应的入库单信息","clientPath":"仓储-入库管理-采购入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.queryWithDetail"},
  "wms.stockout.PurchaseReturn.queryWithDetail": {"method":"wms.stockout.PurchaseReturn.queryWithDetail","category":"采购类","name":"采购退货出库单查询","description":"获取ERP采购退货出库单信息","clientPath":"仓储-出库管理-采购退货-出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.PurchaseReturn.queryWithDetail"},
  "wms.stockin.Purchase.cancel": {"method":"wms.stockin.Purchase.cancel","category":"采购类","name":"采购入库单取消","description":"采购入库单取消","clientPath":"仓储-入库管理-采购入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.cancel"},
  "purchase.PurchaseOrder.cancelOrder": {"method":"purchase.PurchaseOrder.cancelOrder","category":"采购类","name":"采购单取消","description":"取消采购单","clientPath":"采购-采购单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.cancelOrder"},
  "purchase.PurchaseOrder.pending": {"method":"purchase.PurchaseOrder.pending","category":"采购类","name":"采购单停止等待","description":"采购单停止等待","clientPath":"采购-采购单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.pending"},
  "purchase.PurchaseReturn.pending": {"method":"purchase.PurchaseReturn.pending","category":"采购类","name":"采购退货单停止等待","description":"采购退货单停止等待，注意事项: 一次请求退货单数量不可大于500","clientPath":"采购-采购退货管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.pending"},
  "purchase.ProviderGoods.upload": {"method":"purchase.ProviderGoods.upload","category":"采购类","name":"供应商货品推送","description":"推送供应商货品信息","clientPath":"采购--供应商货品","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.ProviderGoods.upload"},
  "wms.stockout.PurchaseReturn.createOrder": {"method":"wms.stockout.PurchaseReturn.createOrder","category":"采购类","name":"采购退货出库单创建","description":"推送采购退货出库单据给ERP","clientPath":"仓储-出库管理-采购退货-出库开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.PurchaseReturn.createOrder"},
  "purchase.PurchaseOrder.updatePurchaseInfo": {"method":"purchase.PurchaseOrder.updatePurchaseInfo","category":"采购类","name":"采购单标记更新","description":"更新ERP采购单标记","clientPath":"采购--采购单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.updatePurchaseInfo"},
  "purchase.PurchaseApply.upload": {"method":"purchase.PurchaseApply.upload","category":"采购类","name":"采购申请单创建","description":"推送采购申请单据给ERP","clientPath":"采购--采购申请开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.upload"},
  "purchase.PurchaseApply.search": {"method":"purchase.PurchaseApply.search","category":"采购类","name":"采购申请单查询","description":"获取ERP内采购申请单数据","clientPath":"采购--采购申请单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.search"},
  "purchase.PurchaseReturn.batchCancelOrder": {"method":"purchase.PurchaseReturn.batchCancelOrder","category":"采购类","name":"采购退货批量取消","description":"推送取消已生成的采购退货单据给ERP","clientPath":"采购-采购退货单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.batchCancelOrder"},
  "finance.settle.Purchase.upload": {"method":"finance.settle.Purchase.upload","category":"采购类","name":"创建采购结算单","description":"推送采购结算单给ERP","clientPath":"账款-单据结算-采购单结算","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Purchase.upload"},
  "purchase.PurchaseOrder.cancelByType": {"method":"purchase.PurchaseOrder.cancelByType","category":"采购类","name":"采购单取消（新）","description":"根据传入的类型进行采购单取消或停止等待","clientPath":"采购-采购单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.cancelByType"},
  "purchase.PurchaseApply.cancelForApi": {"method":"purchase.PurchaseApply.cancelForApi","category":"采购类","name":"采购申请单取消","description":"取消采购申请单","clientPath":"采购-采购申请单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.cancelForApi"},
  "purchase.PurchaseApply.stopForApi": {"method":"purchase.PurchaseApply.stopForApi","category":"采购类","name":"采购申请单停止引用","description":"部分引用状态的采购申请单停止引用","clientPath":"采购-采购申请单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.stopForApi"},
  "purchase.StockInPreOrder.search": {"method":"purchase.StockInPreOrder.search","category":"采购类","name":"预约入库单查询","description":"预入库预约单管理，分页查询接口","clientPath":"采购-入库预约单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.StockInPreOrder.search"},
  "finance.settle.PurchaseReturn.upload": {"method":"finance.settle.PurchaseReturn.upload","category":"采购类","name":"创建采购退货结算单","description":"","clientPath":"账款-单据结算-采购退货结算","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.PurchaseReturn.upload"},
  "wms.MoveOrder.queryWithDetail": {"method":"wms.MoveOrder.queryWithDetail","category":"库存类","name":"移位单查询","description":"获取ERP移位单信息","clientPath":"仓储-移位单-移位单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.MoveOrder.queryWithDetail"},
  "wms.StockSpec.search": {"method":"wms.StockSpec.search","category":"库存类","name":"库存查询","description":"获取ERP单品（sku）的库存量","clientPath":"仓储→库存信息→库存管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.search"},
  "wms.StockPd.stockSyncByPd": {"method":"wms.StockPd.stockSyncByPd","category":"库存类","name":"创建盘点单","description":"ERP库存需要调整时，推送盘点库存单据给ERP","clientPath":"仓储-货品盘点","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.stockSyncByPd"},
  "wms.stockin.Other.createOtherOrder": {"method":"wms.stockin.Other.createOtherOrder","category":"库存类","name":"其它入库单新建","description":"ERP需要增加库存且入库单据没有对应的业务类型，推送其它入库单给ERP","clientPath":"仓储-入库管理-其它入库-入库开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Other.createOtherOrder"},
  "wms.stocktransfer.Manage.queryWithDetail": {"method":"wms.stocktransfer.Manage.queryWithDetail","category":"库存类","name":"调拨单查询","description":"获取ERP的调拨单据信息","clientPath":"仓储-货品调拨-调拨单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Manage.queryWithDetail"},
  "wms.stockout.OtherQuery.queryWithDetail": {"method":"wms.stockout.OtherQuery.queryWithDetail","category":"库存类","name":"其它出库单查询","description":"获取ERP其它出库单信息","clientPath":"仓储-出库管理--其它出库-出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.OtherQuery.queryWithDetail"},
  "wms.stockin.Other.queryWithDetail": {"method":"wms.stockin.Other.queryWithDetail","category":"库存类","name":"其它入库单查询","description":"获取ERP其它入库单单据信息","clientPath":"仓储-入库管理--其它入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Other.queryWithDetail"},
  "wms.stockin.Transfer.queryWithDetail": {"method":"wms.stockin.Transfer.queryWithDetail","category":"库存类","name":"调拨入库单查询","description":"获取ERP调拨入库单单据信息","clientPath":"仓储-入库管理-调拨入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Transfer.queryWithDetail"},
  "wms.StockSpec.queryAvailableStock": {"method":"wms.StockSpec.queryAvailableStock","category":"库存类","name":"可用库存查询","description":"获取ERP内单品的可用库存量","clientPath":"仓储→库存信息→可用库存","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.queryAvailableStock"},
  "wms.stockout.Other.createOther": {"method":"wms.stockout.Other.createOther","category":"库存类","name":"其它出库单新建","description":"ERP需要减少库存且出库单据没有对应的业务类型，推送其它出库单给ERP","clientPath":"仓储-出库管理-其它出库-出库开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Other.createOther"},
  "wms.stockout.Transfer.queryWithDetail": {"method":"wms.stockout.Transfer.queryWithDetail","category":"库存类","name":"调拨出库单查询","description":"获取ERP调拨出库单信息","clientPath":"仓储-出库管理-调拨出库-出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Transfer.queryWithDetail"},
  "wms.stockin.Transfer.cancelOrder": {"method":"wms.stockin.Transfer.cancelOrder","category":"库存类","name":"调拨单入库取消","description":"取消预调拨入库单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Transfer.cancelOrder"},
  "wms.StockPd.queryStockPdInDetail": {"method":"wms.StockPd.queryStockPdInDetail","category":"库存类","name":"盘点入库单查询","description":"获取ERP盘点入库单信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPdInDetail"},
  "wms.StockPd.queryStockPdOutDetail": {"method":"wms.StockPd.queryStockPdOutDetail","category":"库存类","name":"盘点出库单查询","description":"获取ERP盘点出库单信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPdOutDetail"},
  "wms.stockout.Transfer.cancelOrder": {"method":"wms.stockout.Transfer.cancelOrder","category":"库存类","name":"调拨单出库取消","description":"取消预调拨出库单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Transfer.cancelOrder"},
  "wms.stocktransfer.Manage.cancelOrder": {"method":"wms.stocktransfer.Manage.cancelOrder","category":"库存类","name":"调拨单取消","description":"取消预调拨单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Manage.cancelOrder"},
  "wms.stockin.Transfer.createOrder": {"method":"wms.stockin.Transfer.createOrder","category":"库存类","name":"调拨入库单新建","description":"推送调拨入库单据给ERP","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Transfer.createOrder"},
  "wms.stockout.Transfer.createOrder": {"method":"wms.stockout.Transfer.createOrder","category":"库存类","name":"调拨出库单新建","description":"推送调拨出库单据给ERP","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Transfer.createOrder"},
  "wms.stocktransfer.Edit.createOrder": {"method":"wms.stocktransfer.Edit.createOrder","category":"库存类","name":"调拨单新建","description":"推送调拨单给ERP","clientPath":"仓储-货品调拨-调拨开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Edit.createOrder"},
  "wms.StockShelve.queryWithDetail": {"method":"wms.StockShelve.queryWithDetail","category":"库存类","name":"补货单查询","description":"查询补货单","clientPath":"仓储-货品上架-补货单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockShelve.queryWithDetail"},
  "wms.StockSpec.queryChangeHistory": {"method":"wms.StockSpec.queryChangeHistory","category":"库存类","name":"库存变化查询","description":"获取ERP库存变化信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.queryChangeHistory"},
  "finance.StockCost.search": {"method":"finance.StockCost.search","category":"库存类","name":"存货成本查询","description":"获取ERP内存货成本信息","clientPath":"账款-收入成本-存货成本","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.StockCost.search"},
  "wms.stocktransfer.Manage.pending": {"method":"wms.stocktransfer.Manage.pending","category":"库存类","name":"调拨单停止等待","description":"调拨单停止等待","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Manage.pending"},
  "wms.stockother.Out.push": {"method":"wms.stockother.Out.push","category":"库存类","name":"其它出库业务单创建","description":"其它出库业务单创建","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.Out.push"},
  "wms.stockother.In.push": {"method":"wms.stockother.In.push","category":"库存类","name":"其它入库业务单创建","description":"其它入库业务单创建","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.In.push"},
  "wms.stockout.Process.queryWithDetail": {"method":"wms.stockout.Process.queryWithDetail","category":"库存类","name":"生产出库查询","description":"获取ERP生产出库信息","clientPath":"仓储-出库管理-生产出库-出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Process.queryWithDetail"},
  "wms.stockin.Process.queryWithDetail": {"method":"wms.stockin.Process.queryWithDetail","category":"库存类","name":"生产入库查询","description":"获取ERP生产入库信息，注意事项：传入参数如果没有入库单号或者生产单号，就必须传入时间，和时间类型作为参数","clientPath":"仓储-入库管理-生产入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Process.queryWithDetail"},
  "wms.outer.OuterOut.createOrder": {"method":"wms.outer.OuterOut.createOrder","category":"库存类","name":"外仓调整出库单创建","description":"外仓调整出库单创建","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterOut.createOrder"},
  "wms.outer.OuterIn.createOrder": {"method":"wms.outer.OuterIn.createOrder","category":"库存类","name":"外仓调整入库单创建","description":"外仓调整入库单创建","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterIn.createOrder"},
  "wms.outer.OuterOut.queryWithDetail": {"method":"wms.outer.OuterOut.queryWithDetail","category":"库存类","name":"外仓调整出库单查询","description":"获取ERP外仓调整出库信息","clientPath":"仓储-外仓调整-调整出库-出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterOut.queryWithDetail"},
  "wms.outer.OuterIn.queryWithDetail": {"method":"wms.outer.OuterIn.queryWithDetail","category":"库存类","name":"外仓调整入库单查询","description":"获取ERP外仓调整入信息","clientPath":"仓储-外仓调整-调整入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterIn.queryWithDetail"},
  "finance.settle.Transfer.search": {"method":"finance.settle.Transfer.search","category":"库存类","name":"调拨结算查询","description":"获取ERP调拨结算单信息","clientPath":"账款-单据结算-调拨结算","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Transfer.search"},
  "wms.stockdefect.DefectChange.search": {"method":"wms.stockdefect.DefectChange.search","category":"库存类","name":"正残转换单查询","description":"获取ERP正残转换单信息","clientPath":"仓储--正残转换--正残转换单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockdefect.DefectChange.search"},
  "wms.stockother.OutQuery.queryWithDetail": {"method":"wms.stockother.OutQuery.queryWithDetail","category":"库存类","name":"其它出库业务单查询","description":"获取ERP其它出库业务单信息","clientPath":"仓储--其它出库业务--其它出库业务管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.OutQuery.queryWithDetail"},
  "wms.stockother.InQuery.queryWithDetail": {"method":"wms.stockother.InQuery.queryWithDetail","category":"库存类","name":"其它入库业务单查询","description":"获取ERP其它入库业务单单据信息","clientPath":"仓储--其它入库业务--其它入库业务管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.InQuery.queryWithDetail"},
  "wms.stockout.SalesPick.pickListOverviewForApi": {"method":"wms.stockout.SalesPick.pickListOverviewForApi","category":"库存类","name":"分拣单全览","description":"分拣波次查询","clientPath":"仓储--销售出库--波次管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.SalesPick.pickListOverviewForApi"},
  "wms.PositionCapacity.search": {"method":"wms.PositionCapacity.search","category":"库存类","name":"默认货位查询","description":"获取ERP单品（sku）默认货位","clientPath":"仓储--货品上架--拣货货位管理/备货货位管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.PositionCapacity.search"},
  "setting.strategy.VirtualWarehouse.stockSearch": {"method":"setting.strategy.VirtualWarehouse.stockSearch","category":"库存类","name":"虚拟仓库存查询","description":"获取虚拟仓库存信息","clientPath":"设置--策略设置--虚拟仓策略--虚拟仓库存","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.stockSearch"},
  "setting.strategy.VirtualWarehouse.create": {"method":"setting.strategy.VirtualWarehouse.create","category":"库存类","name":"虚拟仓单据创建","description":"创建虚拟仓订单给ERP","clientPath":"设置--策略设置--虚拟仓策略--虚拟仓单据","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.create"},
  "setting.strategy.VirtualWarehouse.orderSearch": {"method":"setting.strategy.VirtualWarehouse.orderSearch","category":"库存类","name":"虚拟仓单据查询","description":"查询虚拟仓单据信息","clientPath":"设置--策略设置--虚拟仓策略--虚拟仓单据","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.orderSearch"},
  "wms.stockout.Pack.search": {"method":"wms.stockout.Pack.search","category":"库存类","name":"装箱单查询","description":"查询系统内非jit类型的装箱单","clientPath":"仓储--出库装箱--装箱单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Pack.search"},
  "wms.stockin.JitRefund.searchOrderWithDetail": {"method":"wms.stockin.JitRefund.searchOrderWithDetail","category":"库存类","name":"JIT退货入库单查询","description":"获取ERP内JIT退货入库单数据","clientPath":"仓储--入库管理--JIT退货入库--入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.JitRefund.searchOrderWithDetail"},
  "wms.stockout.JitOrder.search": {"method":"wms.stockout.JitOrder.search","category":"库存类","name":"JIT出库单查询","description":"获取ERP内JIT出库单数据","clientPath":"仓储--出库管理--JIT出库--出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.JitOrder.search"},
  "wms.GoodsSN.queryWithDetail": {"method":"wms.GoodsSN.queryWithDetail","category":"库存类","name":"SN码查询","description":"获取ERP序列号管理页面的数据","clientPath":"仓储--流通码管理--序列号管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.GoodsSN.queryWithDetail"},
  "finance.settle.OtherIn.upload": {"method":"finance.settle.OtherIn.upload","category":"库存类","name":"其它入库业务结算单创建","description":"创建其它入库业务结算单","clientPath":"账款--单据结算--其它结算--入库业务结算","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.OtherIn.upload"},
  "wms.StockSpec.search2": {"method":"wms.StockSpec.search2","category":"库存类","name":"库存查询2","description":"获取ERP单品的库存量","clientPath":"仓储--库存信息--库存管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.search2"},
  "statistic.StockoutCollect.queryCostWithDetail": {"method":"statistic.StockoutCollect.queryCostWithDetail","category":"库存类","name":"出库瞬时成本查询","description":"获取ERP出库瞬时成本信息","clientPath":"统计--库存--出库瞬时成本","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=statistic.StockoutCollect.queryCostWithDetail"},
  "statistic.StockinCollect.queryCostWithDetail": {"method":"statistic.StockinCollect.queryCostWithDetail","category":"库存类","name":"入库瞬时成本查询","description":"获取ERP入库瞬时成本信息","clientPath":"统计--库存--入库瞬时成本","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=statistic.StockinCollect.queryCostWithDetail"},
  "wms.StockPd.queryStockPd": {"method":"wms.StockPd.queryStockPd","category":"库存类","name":"盘点单查询","description":"获取ERP盘点单数据","clientPath":"仓储--货品盘点--盘点单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPd"},
  "wms.StockPd.queryStockPdDetail": {"method":"wms.StockPd.queryStockPdDetail","category":"库存类","name":"盘点单明细查询","description":"获取ERP的盘点单明细数据","clientPath":"仓储--货品盘点--盘点单管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPdDetail"},
  "wms.stockin.Base.search": {"method":"wms.stockin.Base.search","category":"库存类","name":"入库单查询","description":"查询入库单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Base.search"},
  "wms.stockout.Base.search": {"method":"wms.stockout.Base.search","category":"库存类","name":"出库单查询","description":"查询出库单","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Base.search"},
  "wms.StockSpec.stockDetailSearch": {"method":"wms.StockSpec.stockDetailSearch","category":"库存类","name":"库存明细查询","description":"库存管理页面下明细库存tab","clientPath":"仓储-库存信息-库存管理-明细库存tab","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.stockDetailSearch"},
  "wms.stockout.Base.searchSN": {"method":"wms.stockout.Base.searchSN","category":"库存类","name":"出库SN查询","description":"获取已出库的SN信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Base.searchSN"},
  "wms.stockin.Base.searchSN": {"method":"wms.stockin.Base.searchSN","category":"库存类","name":"入库SN查询","description":"查询入库SN信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Base.searchSN"},
  "wms.stockin.Base.uploadSN": {"method":"wms.stockin.Base.uploadSN","category":"库存类","name":"入库SN明细推送","description":"针对已经创建好的入库单，推送关联的SN信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Base.uploadSN"},
  "wms.stockout.Base.uploadSN": {"method":"wms.stockout.Base.uploadSN","category":"库存类","name":"出库SN明细推送","description":"针对已经创建好的出库单，推送关联的SN信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Base.uploadSN"},
  "wms.stockin.Other.cancelOtherOrder": {"method":"wms.stockin.Other.cancelOtherOrder","category":"库存类","name":"其它入库单取消","description":"取消待审核或者编辑中状态的其它入库单","clientPath":"仓储-入库管理--其它入库-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Other.cancelOtherOrder"},
  "wms.stockout.Other.cancelOtherOrder": {"method":"wms.stockout.Other.cancelOtherOrder","category":"库存类","name":"其它出库单取消","description":"取消待审核或未确认状态的其它出库单","clientPath":"仓储-出库管理--其它出库-出库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Other.cancelOtherOrder"},
  "finance.settle.Logistics.search": {"method":"finance.settle.Logistics.search","category":"库存类","name":"电子面单号查询","description":"查询电子面单号管理数据","clientPath":"仓储-电子面单号管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Logistics.search"},
  "wms.GoodsPack.upload": {"method":"wms.GoodsPack.upload","category":"库存类","name":"箱码新建","description":"创建箱码信息","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.GoodsPack.upload"},
  "wms.stockother.In.cancelOrder": {"method":"wms.stockother.In.cancelOrder","category":"库存类","name":"其它入库业务单据取消","description":"其它入库业务单据取消 支持取消\"已审核\"、\"待审核\"、\"编辑中\"状态的单据","clientPath":"仓储--其它入库业务--其它入库业务管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.In.cancelOrder"},
  "wms.stockother.Out.cancelOrder": {"method":"wms.stockother.Out.cancelOrder","category":"库存类","name":"其它出库业务单据取消","description":"其它出库业务单据取消 支持取消\"已审核\"、\"待审核\"、\"编辑中\"状态的单据","clientPath":"仓储--其它出库业务--其它出库业务管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.Out.cancelOrder"},
  "setting.strategy.VirtualWarehouse.strategyAllocationCreate": {"method":"setting.strategy.VirtualWarehouse.strategyAllocationCreate","category":"库存类","name":"虚拟仓库存分配策略创建","description":"虚拟仓库存分配, 功能类似于客户端: 设置-策略设置-虚拟仓策略-虚拟仓库存分配","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.strategyAllocationCreate"},
  "setting.strategy.VirtualWarehouse.reserveExtractAdd": {"method":"setting.strategy.VirtualWarehouse.reserveExtractAdd","category":"库存类","name":"虚拟仓库存释放策略新建","description":"虚拟仓库存分配, 功能类似于客户端: 设置-策略设置-虚拟仓策略-虚拟仓库存分配","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.reserveExtractAdd"},
  "wms.outer.OuterTransfer.createByApi": {"method":"wms.outer.OuterTransfer.createByApi","category":"库存类","name":"外仓快速调拨","description":"外仓快速调拨","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterTransfer.createByApi"},
  "wms.GoodsBatch.createByApi": {"method":"wms.GoodsBatch.createByApi","category":"库存类","name":"批次号创建","description":"创建批次号","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.GoodsBatch.createByApi"},
  "setting.strategy.VirtualWarehouse.strategyAllocationQuery": {"method":"setting.strategy.VirtualWarehouse.strategyAllocationQuery","category":"库存类","name":"虚拟仓库存分配策略查询","description":"获取虚拟仓库存分配查询接口的数据","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.strategyAllocationQuery"},
  "wms.ErrorCorrection.queryWithDetail": {"method":"wms.ErrorCorrection.queryWithDetail","category":"库存类","name":"纠错单查询","description":"获取ERP纠错管理页面的数据","clientPath":"仓储--纠错管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.ErrorCorrection.queryWithDetail"},
  "wms.stockin.Refund.queryWithDetail": {"method":"wms.stockin.Refund.queryWithDetail","category":"售后类","name":"退货入库单查询","description":"获取ERP的退货入库单单据信息","clientPath":"仓储-入库管理-销售退货-入库管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.queryWithDetail"},
  "aftersales.refund.RawRefund.upload": {"method":"aftersales.refund.RawRefund.upload","category":"售后类","name":"原始退款单推送","description":"该接口不做新增系统退换单使用，该接口可以更新售后单退货物流信息、更新退货金额、变更退换类型等","clientPath":"销售-售后管理-原始退款单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.upload"},
  "wms.stockin.PreStockin.createExt": {"method":"wms.stockin.PreStockin.createExt","category":"售后类","name":"创建退货预入库","description":"推送退货预入库单据给ERP","clientPath":"仓储-入库管理-销售退货-预入库单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.PreStockin.createExt"},
  "aftersales.refund.Refund.search": {"method":"aftersales.refund.Refund.search","category":"售后类","name":"退换单查询","description":"获取ERP销售退货（换货）订单信息","clientPath":"销售-售后管理-退换管理","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.Refund.search"},
  "wms.stockin.PreStockin.search": {"method":"wms.stockin.PreStockin.search","category":"售后类","name":"预入库单据查询","description":"获取ERP预入库单单据信息","clientPath":"仓储-入库管理-销售退货-预入库单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.PreStockin.search"},
  "wms.stockin.PreStockin.cancel": {"method":"wms.stockin.PreStockin.cancel","category":"售后类","name":"退货预入库单取消","description":"取消预入库单","clientPath":"仓储-入库管理-销售退货-预入库单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.PreStockin.cancel"},
  "aftersales.refund.Refund.searchHistory": {"method":"aftersales.refund.Refund.searchHistory","category":"售后类","name":"历史退换单查询","description":"查询已经归档的退换单信息","clientPath":"销售-历史订单-历史退换单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.Refund.searchHistory"},
  "aftersales.refund.RawRefund.search": {"method":"aftersales.refund.RawRefund.search","category":"售后类","name":"原始退款单查询","description":"获取ERP原始退款单数据","clientPath":"销售--售后管理--原始退款单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.search"},
  "aftersales.refund.RawRefund.upload2": {"method":"aftersales.refund.RawRefund.upload2","category":"售后类","name":"原始退款单推送2","description":"推送自有平台原始退款单给ERP","clientPath":"销售-售后管理-原始退款单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.upload2"},
  "wms.stockin.Refund.createOrder": {"method":"wms.stockin.Refund.createOrder","category":"售后类","name":"退货入库单推送","description":"推送退货入库单给ERP","clientPath":"仓储--入库管理--销售退货--入库开单","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.createOrder"},
  "wms.stockin.SmartRefund.upload": {"method":"wms.stockin.SmartRefund.upload","category":"售后类","name":"快速退货","description":"推送快速退货单据信息给ERP","clientPath":"仓储-入库管理-销售退货-快速入库","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.SmartRefund.upload"},
  "wms.stockin.Refund.queryHisWithDetail": {"method":"wms.stockin.Refund.queryHisWithDetail","category":"售后类","name":"历史退货入库单查询","description":"获取已归档的退货入库单数据","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.queryHisWithDetail"},
  "aftersales.refund.RawRefund.searchHistory": {"method":"aftersales.refund.RawRefund.searchHistory","category":"售后类","name":"历史原始退款单查询","description":"获取ERP已归档的原始退款单数据","clientPath":"","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.searchHistory"},
  "wms.stockin.Refund.returnLogisticsPackageQuery": {"method":"wms.stockin.Refund.returnLogisticsPackageQuery","category":"售后类","name":"退货物流包裹查询","description":"退货物流分页查询","clientPath":"仓储-入库管理-退货物流登记","docUrl":"https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.returnLogisticsPackageQuery"},
} as const satisfies Record<string, WdtEndpointMeta>;

export type WdtMethod = keyof typeof WDT_ENDPOINTS;

export interface WdtEndpointMap {
  "wms.stockout.Sales.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.LogisticsSync.update": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.RawTrade.pushSelf": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.LogisticsSync.getSyncListExt": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.weighingExt": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.onceWeighing": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.invoice.InvoiceOrder.search": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.invoice.InvoiceOrder.updateInvoice": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.RawPayment.search": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.RawPayment.push": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.StockSync.cancelSync": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.StockSync.syncFail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.StockSync.syncSuccess": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.StockSync.getSelfWaitSyncIdListOpen": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.queryHistoryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.queryHistoryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.AlipayAccountCheck.search": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.RawTrade.search": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.getTradeMergedLog": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.Payment.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.onceWeighingByNo": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.StockSync.calcStock": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.salesWeighing": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeEdit.modifyRemark": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.searchLogistics": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.RawTrade.searchHistory": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.jit.JitRefund.search": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.RawTrade.pushSelf2": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.searchPositionDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.Payment.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeImport.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Sales.searchCancel": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.getLog": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.CustomAttr.getTradeLabel": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeEdit.toException": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.StockSync.batchCalcStock": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.querySelfOrderWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.RawTrade.searchHistorySelfOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.queryHistorySelfOrderWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.RawTrade.searchSelfOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeQuery.getLog2": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Logistics.queryLogistics": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.PurchaseProvider.queryDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Warehouse.queryWarehouse": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Shop.queryShop": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.PurchaseProvider.push": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Shop.updateShop": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Employee.search": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.warehouseSearch": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.OperationReason.search": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Address.provinceSearch": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Address.citySearch": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.Address.districtSearch": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.query": { request: WdtRequestBody; response: WdtApiResponse };
  "sales.TradeEdit.uploadChangeGoodsByApi": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Goods.push": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Suite.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Goods.queryWithSpec": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.ApiGoods.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.ApiGoods.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "process.Bom.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "process.Process.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "process.Process.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.GoodsClass.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.GoodsBrand.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Suite.upload2": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Category.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Goods.batchPush": { request: WdtRequestBody; response: WdtApiResponse };
  "process.Bom.search": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Barcode.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.Goods.push2": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.GoodsClass.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "goods.GoodsBrand.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.process.search": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.ProviderGoods.queryDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseReturn.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseReturn.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseReturn.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Purchase.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseOrder.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseOrder.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.Purchase.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Purchase.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.PurchaseReturn.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Purchase.cancel": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseOrder.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseOrder.pending": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseReturn.pending": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.ProviderGoods.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.PurchaseReturn.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseOrder.updatePurchaseInfo": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseApply.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseApply.search": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseReturn.batchCancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.Purchase.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseOrder.cancelByType": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseApply.cancelForApi": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.PurchaseApply.stopForApi": { request: WdtRequestBody; response: WdtApiResponse };
  "purchase.StockInPreOrder.search": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.PurchaseReturn.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.MoveOrder.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockSpec.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockPd.stockSyncByPd": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Other.createOtherOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stocktransfer.Manage.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.OtherQuery.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Other.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Transfer.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockSpec.queryAvailableStock": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Other.createOther": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Transfer.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Transfer.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockPd.queryStockPdInDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockPd.queryStockPdOutDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Transfer.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stocktransfer.Manage.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Transfer.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Transfer.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stocktransfer.Edit.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockShelve.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockSpec.queryChangeHistory": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.StockCost.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stocktransfer.Manage.pending": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockother.Out.push": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockother.In.push": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Process.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Process.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.outer.OuterOut.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.outer.OuterIn.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.outer.OuterOut.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.outer.OuterIn.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.Transfer.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockdefect.DefectChange.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockother.OutQuery.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockother.InQuery.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.SalesPick.pickListOverviewForApi": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.PositionCapacity.search": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.stockSearch": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.create": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.orderSearch": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Pack.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.JitRefund.searchOrderWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.JitOrder.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.GoodsSN.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.OtherIn.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockSpec.search2": { request: WdtRequestBody; response: WdtApiResponse };
  "statistic.StockoutCollect.queryCostWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "statistic.StockinCollect.queryCostWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockPd.queryStockPd": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockPd.queryStockPdDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Base.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Base.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.StockSpec.stockDetailSearch": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Base.searchSN": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Base.searchSN": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Base.uploadSN": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Base.uploadSN": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Other.cancelOtherOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockout.Other.cancelOtherOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "finance.settle.Logistics.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.GoodsPack.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockother.In.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockother.Out.cancelOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.strategyAllocationCreate": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.reserveExtractAdd": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.outer.OuterTransfer.createByApi": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.GoodsBatch.createByApi": { request: WdtRequestBody; response: WdtApiResponse };
  "setting.strategy.VirtualWarehouse.strategyAllocationQuery": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.ErrorCorrection.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Refund.queryWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "aftersales.refund.RawRefund.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.PreStockin.createExt": { request: WdtRequestBody; response: WdtApiResponse };
  "aftersales.refund.Refund.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.PreStockin.search": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.PreStockin.cancel": { request: WdtRequestBody; response: WdtApiResponse };
  "aftersales.refund.Refund.searchHistory": { request: WdtRequestBody; response: WdtApiResponse };
  "aftersales.refund.RawRefund.search": { request: WdtRequestBody; response: WdtApiResponse };
  "aftersales.refund.RawRefund.upload2": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Refund.createOrder": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.SmartRefund.upload": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Refund.queryHisWithDetail": { request: WdtRequestBody; response: WdtApiResponse };
  "aftersales.refund.RawRefund.searchHistory": { request: WdtRequestBody; response: WdtApiResponse };
  "wms.stockin.Refund.returnLogisticsPackageQuery": { request: WdtRequestBody; response: WdtApiResponse };
}
